CREATE TABLE EMPLOYEE (
    SSN INT PRIMARY KEY,
    FNAME VARCHAR(20),
    LNAME VARCHAR(20),
    bdate  DATE,
    ADDRESS VARCHAR(50),
    sex VARCHAR(1),
    salary DECIMAL(10,2),
    SUPERSSN int ,
    dno int


);
CREATE TABLE DEPARTMENT(
    DNUMBER int PRIMARY KEY,
     DNAME VARCHAR(20),
     MGRSSN int  FOREIGN KEY  REFERENCES  EMPLOYEE(ssn)  ,
     MGRSTARTDATE DATE 
 
 
 );
CREATE TABLE DEPT_LOCATIONS (
    DNUMBER int,
    DLOCATION VARCHAR(20),
    PRIMARY KEY (DNUMBER, DLOCATION),
    FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
);
CREATE TABLE PROJECT(


    PNAME VARCHAR(20) ,
    PNUMBER int PRIMARY KEY ,
    PLOCATION VARCHAR(20),
    DNUM int  FOREIGN KEY REFERENCES DEPARTMENT(DNUMBER) 


);
CREATE TABLE WORKS_ON (

    essn int ,
    pno int ,
      HOURS DECIMAL(5,2),
     PRIMARY KEY(essn ,pno),
      FOREIGN KEY (essn)REFERENCES EMPLOYEE (ssn),
      FOREIGN KEY (pno) REFERENCES PROJECT (PNUMBER)
    

);
CREATE TABLE DEPENDENT (
    essn int , 
DEPENDENT_name VARCHAR(20),
 PRIMARY KEY( essn ,DEPENDENT_name),

sex VARCHAR(1),
bdate DATE ,
relationship VARCHAR(20) ,
FOREIGN KEY(essn )REFERENCES EMPLOYEE (ssn)

);
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, BDATE, ADDRESS, SEX, SALARY, SUPERSSN, DNO)
VALUES
(100, 'Ahmed', 'Hassan', '1980-05-10', 'Cairo', 'M', 8000.00, NULL, NULL),
(101, 'Sara', 'Mostafa', '1985-03-22', 'Alex', 'F', 7500.00, 100, NULL),
(102, 'Omar', 'Khaled', '1990-07-15', 'Giza', 'M', 6000.00, 100, NULL),
(103, 'Mona', 'Adel', '1988-11-02', 'Cairo', 'F', 6500.00, 101, NULL),
(104, 'Khaled', 'Fathy', '1992-01-30', 'Mansoura', 'M', 5500.00, 101, NULL);
SELECT * 
FROM EMPLOYEE;
INSERT INTO DEPARTMENT (DNUMBER, DNAME, MGRSSN, MGRSTARTDATE)
VALUES
(10, 'Research', 100, '2015-01-01'),
(20, 'Admin', 101, '2018-06-15'),
(30, 'Sales', 102, '2020-03-10');
UPDATE EMPLOYEE SET DNO = 10 WHERE SSN IN (100, 101);
UPDATE EMPLOYEE SET DNO = 20 WHERE SSN IN (102, 103);
UPDATE EMPLOYEE SET DNO = 30 WHERE SSN = 104;


INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION)
VALUES
(10, 'Cairo'),
(10, 'Alex'),
(20, 'Giza'),
(30, 'Mansoura');
INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES
('ProjectA', 1, 'Cairo', 10),
('ProjectB', 2, 'Alex', 10),
('ProjectC', 3, 'Giza', 20),
('ProjectD', 4, 'Mansoura', 30);
INSERT INTO WORKS_ON (essn, pno, HOURS)
VALUES
(100, 1, 20.5),
(101, 1, 15.0),
(102, 2, 30.0),
(103, 3, 10.5),
(104, 4, 25.0);
INSERT INTO DEPENDENT (essn, DEPENDENT_name, sex, bdate, relationship)
VALUES
(100, 'Yasmin', 'F', '2010-04-12', 'Daughter'),
(101, 'Karim', 'M', '2012-09-05', 'Son'),
(102, 'Nour', 'F', '2015-02-20', 'Daughter');
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM DEPT_LOCATIONS;
SELECT * FROM PROJECT;
SELECT * FROM WORKS_ON;
SELECT * FROM DEPENDENT;